# Project: custom-string-class
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o String.o
LINKOBJ  = main.o String.o
LIBS     = -L"C:/Users/gcornea/Documents/Concept2/mig/Dev-Cpp/MinGW64/lib" -L"C:/Users/gcornea/Documents/Concept2/mig/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/gcornea/Documents/Concept2/mig/Dev-Cpp/MinGW64/include" -I"C:/Users/gcornea/Documents/Concept2/mig/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/gcornea/Documents/Concept2/mig/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/gcornea/Documents/Concept2/mig/Dev-Cpp/MinGW64/include" -I"C:/Users/gcornea/Documents/Concept2/mig/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/gcornea/Documents/Concept2/mig/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/gcornea/Documents/Concept2/mig/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = custom-string-class.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

String.o: String.cpp
	$(CPP) -c String.cpp -o String.o $(CXXFLAGS)
